# ========================================
# GENESIS LUMINAL - DEPENDABOT CONFIG
# Backup para dependency updates
# ========================================

version: 2
updates:
  # Backend Dependencies
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    reviewers:
      - "PrinceOfEgypt1"
    assignees:
      - "PrinceOfEgypt1"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    versioning-strategy: increase

  # Frontend Dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    reviewers:
      - "PrinceOfEgypt1"
    assignees:
      - "PrinceOfEgypt1"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    versioning-strategy: increase

  # Root Dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 3
    reviewers:
      - "PrinceOfEgypt1"
    labels:
      - "dependencies"
      - "root"
    commit-message:
      prefix: "chore(deps)"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 2
    reviewers:
      - "PrinceOfEgypt1"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(deps)"
