#!/bin/bash

echo "🔐 GENESIS LUMINAL - SECRET MANAGER SETUP"
echo "=========================================="
echo ""

echo "✅ Secret Manager configurado para desenvolvimento local"
echo ""
echo "📋 Configuração atual:"
echo "- Provider: Local (fallback para environment variables)"
echo "- Rotação: Desabilitada (desenvolvimento)"
echo "- Detecção: Ativa via Git hooks"
echo ""
echo "🚀 Para testar:"
echo "1. cd backend"
echo "2. npm run build"
echo "3. npm run dev"
echo ""
echo "⚠️ Em produção, configure um provedor real (Azure/AWS/GCP)"
echo ""
echo "✅ Setup concluído!"
